In [ ]:
# tushare + backtesting

In [ ]:
''' Tushare
Grid Strategy实盘怎么接
写trend following
写MA
写RSI

vvnpy, vnstation app
microsoft pyqlib

'''

In [ ]:
import tushare as ts
pro = ts.pro_api('751c24755913f41ceb47461453aafde3a1e0e3e038ec11f6faa2efdf')    # Mytoken, keep it safe

In [ ]:
#                      '000001.SZ'
df = pro.daily(ts_code='000001.SZ,600000.SH', start_date='20180701', end_date='20180718')
df

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount
0,000001.SZ,20180718,8.75,8.85,8.69,8.70,8.72,-0.02,-0.23,525152.77,460697.377
1,000001.SZ,20180717,8.74,8.75,8.66,8.72,8.73,-0.01,-0.11,375356.33,326396.994
2,000001.SZ,20180716,8.85,8.90,8.69,8.73,8.88,-0.15,-1.69,689845.58,603427.713
3,000001.SZ,20180713,8.92,8.94,8.82,8.88,8.88,0.00,0.00,603378.21,535401.175
4,000001.SZ,20180712,8.60,8.97,8.58,8.88,8.64,0.24,2.78,1140492.31,1008658.828
5,000001.SZ,20180711,8.76,8.83,8.68,8.78,8.98,-0.20,-2.23,851296.70,744765.824
6,000001.SZ,20180710,9.02,9.02,8.89,8.98,9.03,-0.05,-0.55,896862.02,803038.965
7,000001.SZ,20180709,8.69,9.03,8.68,9.03,8.66,0.37,4.27,1409954.60,1255007.609
8,000001.SZ,20180706,8.61,8.78,8.45,8.66,8.60,0.06,0.70,988282.69,852071.526
9,000001.SZ,20180705,8.62,8.73,8.55,8.60,8.61,-0.01,-0.12,835768.77,722169.579
10,000001.SZ,20180704,8.63,8.75,8.61,8.61,8.67,-0.06,-0.69,711153.37,617278.559
11,000001.SZ,20180703,8.69,8.70,8.45,8.67,8.61,0.06,0.70,1274838.57,1096657.033
12,000001.SZ,20180702,9.05,9.05,8.55,8.61,9.09,-0.48,-5.28,1315520.13,1158545.868

In [ ]:
df = pro.daily(trade_date='20260324')
df.to_csv("stock_list_ts_20260324.csv", index=False, encoding="utf-8-sig")
df

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount
0,000001.SZ,20260324,10.52,10.89,10.52,10.88,10.45,0.43,4.1148,1622251.27,1744746.708
1,000002.SZ,20260324,4.09,4.11,4.02,4.09,4.02,0.07,1.7413,915312.66,371679.205
2,000004.SZ,20260324,4.81,5.24,4.75,5.16,5.00,0.16,3.2000,114291.40,55378.864
3,000006.SZ,20260324,8.29,8.46,8.15,8.44,8.12,0.32,3.9409,233189.83,193471.510
4,000007.SZ,20260324,13.59,13.89,13.46,13.85,13.20,0.65,4.9242,78219.05,107101.859
...,...,...,...,...,...,...,...,...,...,...,...
5476,920978.BJ,20260324,24.33,24.58,23.05,24.58,23.76,0.82,3.4512,25767.97,61989.929
5477,920981.BJ,20260324,26.88,27.25,26.39,27.17,26.47,0.70,2.6445,4913.03,13205.263
5478,920982.BJ,20260324,155.50,157.85,154.23,157.59,153.18,4.41,2.8790,6745.11,105217.387
5479,920985.BJ,20260324,8.40,8.73,8.07,8.54,8.58,-0.04,-0.4662,139333.23,116866.818
5480,920992.BJ,20260324,13.58,14.66,13.28,14.66,13.25,1.41,10.6415,24497.40,34174.912

In [9]:
df = pro.stk_mins(ts_code='600000.SH', freq='1min', start_date='2023-08-25 09:00:00', end_date='2023-08-25 19:00:00')
df

,ts_code,trade_time,close,open,high,low,vol,amount
0,600000.SH,2023-08-25 15:00:00,7.05,7.05,7.05,7.05,235500.0,1660275.0
1,600000.SH,2023-08-25 14:59:00,7.05,7.05,7.05,7.05,0.0,0.0
2,600000.SH,2023-08-25 14:58:00,7.05,7.05,7.05,7.05,0.0,0.0
3,600000.SH,2023-08-25 14:57:00,7.05,7.06,7.06,7.05,51800.0,365491.0
4,600000.SH,2023-08-25 14:56:00,7.05,7.05,7.06,7.04,92700.0,653831.0
...,...,...,...,...,...,...,...,...
236,600000.SH,2023-08-25 09:34:00,7.01,7.02,7.02,7.00,120500.0,845311.0
237,600000.SH,2023-08-25 09:33:00,7.01,7.01,7.02,7.00,126000.0,883188.0
238,600000.SH,2023-08-25 09:32:00,7.01,7.02,7.02,6.99,236699.0,1659260.0
239,600000.SH,2023-08-25 09:31:00,7.02,6.99,7.02,6.97,807500.0,5649956.0
240,600000.SH,2023-08-25 09:30:00,6.99,6.99,6.99,6.99,103700.0,724863.0

In [ ]:
df = pro.rt_min(ts_code='600000.SH', freq='1MIN')    # real time min, 2000 credits

Exception: 抱歉，您没有接口访问权限，权限的具体详情访问：https://tushare.pro/document/1?doc_id=108。